import { Fragment } from 'react';
import Head from 'next/head';
import About from '../components/home-page/about';
import Contact from '../components/home-page/contact';
import FeaturedProjects from '../components/home-page/featured-projects';
import Hero from '../components/home-page/hero';
import { getFeaturedProjects } from '../lib/projects-util';

export default function HomePage(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
